### ISSUE TITLE
Troubleshooting CI

### ISSUE THREAD

**Issue by Harmol** [kubediag/kubediag-helm#12]
When I run the installation command, helm reports a syntax error as follows:

```
$ helm install kubediag/kubediag-helm --create-namespace --generate-name --namespace kubediag
......
Error: YAML parse error on kubediag-helm/templates/rbac/aggregated-role.yaml: error converting YAML to JSON: yaml: line 13: did not find expected key
```

Use tools such as Helm Lint to troubleshooting CI problems and ensure the syntax of configuration file is correct.

**Comment by huangjiuyuan** [comment]
Closed by https://github.com/kubediag/kubediag-helm/pull/15
